env:
  browser: true
  es2021: true
extends:
  [plugin:react/recommended, "plugin:react/recommended", standard, prettier]
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins: [react, "@typescript-eslint"]
settings:
  react:
    version: detect
rules:
  no-use-before-define: 0
  react/display-name: 0
  no-unused-vars: 1
  no-console: 1
  react/no-unused-prop-types: 1
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
