export * from './Nav'
export * from './Footer'
export * from './Hero2'
export * from './TextImg/TextImg'
export * from './Landing'
export * from '../svg/SectionDivider'
export * from './AnimOnScroll'
